---
- name: Configure Tunneling
  hosts: localhost
  become: yes   

  tasks:
    # - name: Parse retrieved data
    #   set_fact:
    #     tenant_data_parsed: "{{ tenant_data | from_yaml }}" 
   
    # - name: Debug tenant_data_parsed
    #   debug:
    #     var: tenant_data_parsed

    - name: Ensure eth1 is up
      command: ip link set eth1 up

    - name: Ensure br0 is up
      command: ip link set br0 up

    - name: Creating GRE tunnel on host1 
      block:
        - name: Create tunnel interface
          command: ip tunnel add gre1 mode ipip remote 192.168.38.9 local 192.168.38.8 ttl 255
        - name: Bring up tunnel interface
          command: ip link set gre1 up
        - name: Assign IP to tunnel endpoint
          command: ip addr add 192.168.4.1/30 dev gre1   
      delegate_to: '192.168.38.8'       
      # vars:
      #   self: '192.168.38.8'
      #   peer_host: '192.168.38.9'
      #   local_ip: '192.168.4.1'
      # delegate_to: "192.168.38.8"

    - name: Creating GRE tunnel on host2
      block:
        - name: Create tunnel interface
          command: ip tunnel add gre1 mode ipip remote 192.168.38.8 local 192.168.38.9 ttl 255
        - name: Bring up tunnel interface
          command: ip link set gre1 up
        - name: Assign IP to tunnel endpoint
          command: ip addr add 192.168.4.2/30 dev gre1  
      delegate_to: '192.168.38.9'         
      # when: ansible_host == '192.168.38.9'
      # vars:
      #   self: '192.168.38.9'
      #   peer_host: '192.168.38.8'
      #   local_ip: '192.168.4.2'
      # delegate_to: "192.168.38.9"