---
- name: Deploy Infrastructure with Docker Containers for Edge and Origin Servers
  hosts: localhost
  gather_facts: no
  become: True  # Enable privilege escalation
  become_method: sudo  # Use sudo for privilege escalation

  vars:
    container_num: 1  # Base number for the container
    server_type: "dns"  # 'edge' or 'origin'
    vpc_name: "dns"
    origin_vm_ip: 10.10.10.10
    container_name: "{{ vpc_name }}_container{{ container_num }}"  # Combined name for simplified use
    subnets: ["bri_9"]  # List of bridge names
    hash_name: "{{ container_name | hash('sha1') }}"
    short_name: "{{ hash_name[0:10] }}"
    # container_ip: 


  tasks:
    - name: Check if network namespace exists
      command: ip netns list | grep -w {{ vpc_name }}
      register: ns_check
      failed_when: ns_check.stdout == ""

    - name: Fail if network namespace does not exist
      fail:
        msg: "Namespace {{ vpc_name }} does not exist. Please run 'deploy_infra' to create the namespace first."
      when: ns_check.stdout == ""

    - name: Create NGINX configuration file from template for edge servers
      template:
        src: "nginx-{{ server_type }}.conf.j2"
        dest: "{{ playbook_dir }}/nginx-{{ container_name }}.conf"

    - name: Conditionally create index.html for origin servers
      template:
        src: "index.html.j2"
        dest: "{{ playbook_dir }}/index.html"
      when: server_type == 'origin'

    - name: Build Docker image with custom NGINX config
      community.docker.docker_image:
        name: "{{ container_name }}"
        tag: "latest"
        build:
          path: "{{ playbook_dir }}"
          dockerfile: "Dockerfile-{{ server_type }}"
          args:
            NGINX_CONF: "nginx-{{ container_name }}.conf"
          nocache: true
          rm: true
        state: present
        source: build

    - name: Create and start Docker container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ container_name }}:latest"
        state: started
        network_mode: none
        tty: true
        restart_policy: unless-stopped
        capabilities:
          - NET_ADMIN

    - name: Get container PID
      command: docker inspect --format '{''{.State.Pid}}' "{{ container_name }}"
      register: docker_pid

    - name: Link network namespace of container
      command: ln -sf /proc/{{ docker_pid.stdout }}/ns/net /var/run/netns/{{ container_name }}

    # Loop for setting up veth pairs and attaching them to subnets
    - name: Create veth pair for bridge {{ item }}
      command: ip link add  {{ short_name }} type veth peer name v_{{ short_name }}
      loop: "{{ subnets }}"

    - name: Bring up veth peer in host namespace for bridge {{ item }}
      command: ip link set v_{{ short_name }} up
      loop: "{{ subnets }}"

    - name: Attach veth interface to the bridge {{ item }}
      command: ip link set v_{{ short_name }} master {{ item }}_br
      loop: "{{ subnets }}"

    - name: Assign container network interface to veth for bridge {{ item }}
      command: ip link set {{ short_name }} netns {{ container_name }}
      loop: "{{ subnets }}"

    # - name: Assign IP address to the interface in container namespace for bridge {{ item }}
    #   command: ip netns exec {{ container_name }} ip addr add {{ container_ip }}/24 dev {{ short_name }}
    #   loop: "{{ subnets }}"

    - name: Bring up container network interface in container namespace for bridge {{ item }}
      command: ip netns exec {{ container_name }} ip link set {{ short_name }} up
      loop: "{{ subnets }}"

    - name: Add default route in container
      command: "ip netns exec {{ container_name }} ip route add default via {{ container_ip.split('.')[:-1] | join('.') }}.1 dev {{ short_name }}"
      
        
