FROM 100514735019/customnginx:latest

COPY index.html /var/www/html/index.html
# Argument for custom NGINX config file path
ARG NGINX_CONF

# Copy the custom configuration file from the build context
COPY ${NGINX_CONF} /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
